WebApp01/Controllers/site/WorkplanTreeController.cs
using GeneralModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace WebApp01.Controllers.site
{
    public class WorkplanTreeController : Controller
    {
        private const string WorkplansAPIUri = "http://localhost:49159/api/workplans";
        // GET: WorkplanTree
        public ActionResult Index(int ProjectFilter)
        {
            List<Workplan> wp = new List<Workplan>();
            var filter = new GeneralModels.Filter() { ProjectID = ProjectFilter };

            HttpResponseMessage response = new HttpClient()
                .PostAsJsonAsync<GeneralModels.Filter>(WorkplansAPIUri, filter)
                .GetAwaiter().GetResult();
            if (response.IsSuccessStatusCode)
            {
                wp = response.Content.ReadAsAsync<List<Workplan>>().GetAwaiter().GetResult();
            }

            return View(wp);
        }
    }
}

WebApp01/Controllers/site/WorkstreamViewController.cs
using GeneralModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace WebApp01.Controllers.site
{
    public class WorkstreamViewController : Controller
    {
        private const string WorkstreamsAPIUri = "http://localhost:49159/api/Workstreams";
        // GET: Workstreams
        public ActionResult Index()
        {
            List<Workstream> workstreams = new List<Workstream>();

            HttpResponseMessage response = new HttpClient().GetAsync(WorkstreamsAPIUri)
                .GetAwaiter().GetResult();
            if (response.IsSuccessStatusCode)
            {
                workstreams = response.Content.ReadAsAsync<List<Workstream>>().GetAwaiter().GetResult();
            }

            return View(workstreams);
        }
    }
}

WebApp01/Views/WorkplanTree/Index.cshtml
@model IEnumerable<GeneralModels.Workplan>

@{
    ViewBag.Title = "Index";
}

@Styles.Render("~/Content/workplanStyle.css")

<h2>Workplans</h2>

<h5>
    @Html.ActionLink("Back", "Index", "WorkstreamView")
</h5>

@Html.ActionLink(
    "To table view",
    "Index",
    "WorkplanView",
    new { ProjectFilter = Request.QueryString["ProjectFilter"] },
    null)

@WebApp01.Helpers.TreeHelper.Tree(Model,
    "<h3>{name}</h3>{status}<br/>" + Html.ActionLink("Details", "Index")
    )