WebApp01/Controllers/site/ProjectViewController.cs
using GeneralModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace WebApp01.Controllers.site
{
    public class ProjectViewController : Controller
    {
        private const string ProjectsAPIUri = "http://localhost:49159/api/projects";
        // GET: ProjectView
        public ActionResult Index(int stream)
        {
            List<Project> projects = new List<Project>();

            HttpResponseMessage response = new HttpClient().GetAsync(ProjectsAPIUri + $"/{stream}")
                .GetAwaiter().GetResult();
            if (response.IsSuccessStatusCode)
            {
                projects = response.Content.ReadAsAsync<List<Project>>().GetAwaiter().GetResult();
            }

            return View(projects);
        }
    }
}

WebApp01/Controllers/site/WorkstreamViewController.cs
using GeneralModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace WebApp01.Controllers.site
{
    public class WorkstreamViewController : Controller
    {
        private const string WorkstreamsAPIUri = "http://localhost:49159/api/Workstreams";
        // GET: Workstreams
        public ActionResult Index()
        {
            List<Workstream> workstreams = new List<Workstream>();

            HttpResponseMessage response = new HttpClient().GetAsync(WorkstreamsAPIUri)
                .GetAwaiter().GetResult();
            if (response.IsSuccessStatusCode)
            {
                workstreams = response.Content.ReadAsAsync<List<Workstream>>().GetAwaiter().GetResult();
            }

            return View(workstreams);
        }
    }
}

WebApp01/Views/WorkstreamView/Index.cshtml
@model IEnumerable<GeneralModels.Workstream>

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink("Details", "Index", "ProjectView", new { stream = item.Id }, null)
        </td>
    </tr>
}

</table>